### ISSUE TITLE
Help needed to build the project

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy-labs/cozy-desktop#1050]
I’m trying to build cozy-desktop for ArchLinux. But I don’t know a lot of things about electron and nodejs (except I hate this build/dependency system :p), so I need a bit of help.

So far what I’m doing is:
```
yarn install
yarn build
```
Then I copy over in a new folder the following files/folders (based on https://github.com/cozy-labs/cozy-desktop/blob/master/electron-builder.yml) :
```
core-built/
gui/
node_modules/
package.json
```
Then, I just run `electron` in this new folder. This works, but I’m wondering if I’m not copying too many files over. Am I right that `gui/app.css.map` and `gui/styles/` are not needed (again, based on https://github.com/cozy-labs/cozy-desktop/blob/master/electron-builder.yml)?

What about the `gui/assets/` folder specified as `buildResources`? I suppose this is used to generate icons only?

Finally, my biggest issue is about `node_modules`. This is a ~350MiB folder, which is far too huge for such a “simple” application. I believe this includes modules required for building only. Is there an easy way to only restrict too required modules? I guess parsing `package.json` wouldn’t be enough since it doesn’t account for dependencies’ dependencies (and so on).

**Comment by sebn** [comment]
Hello there! Thank you very much for the packaging work!

You could probably use the `electron-builder --dir` option so you get the exact same files as in our own Windows/macOS/AppImage packages, except they'll be in a plain `dist/linux/` directory (if I remember correctly).
This should be easier than building manually since `electron-builder` will handle everything for you, including the filtering of development dependencies.

Does this help?

**Comment by sebn** [comment]
You can use the `yarn dist --dir` script for this since it actually wraps the electron-builder command.
You can also take a look at the other options, e.g. `yarn dist --help`, in case you want to choose the target architecture, etc...

**Comment by ArchangeGabriel** [comment]
OK, so after a lot of researches and fiddling with it I managed to get something quite nice (from the `dist`, we only care about `resources`, which basically is all the relevant code from the app packed in some `.asar` file).

I’m only missing two parts now, the .desktop files and icons. I can manually extract them from the AppImage and add them to my package, but having a way to build them would be nice.

**Comment by ArchangeGabriel** [comment]
Oh and also, I get an “update error” message on each launch, is there a way to remove update checking?

**Comment by sebn** [comment]
The update error message should not show up anymore on master.

**Comment by sebn** [comment]
Regarding the icons, I don't really have more info than what you already have: electron-builder automatically converts the macOS `gui/assets/icon.icns` for GNU/Linux use and the desktop file is generated automatically, possibly by AppImage, but since electron-builder is able to generate deb/rpm packages I suspect it should be able to generate it too:
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/templates/linux/desktop.tpl

To find out how to convert the icon, maybe running the build with `DEBUG=electron-builder` will give you more info regarding the third-party tool to use...

**Comment by sebn** [comment]
(hope this helps, sorry I can't do more, but I'm quite busy right now...)

**Comment by ArchangeGabriel** [comment]
Seems `dir` does not build the `.desktop` file nor the icons. Well I will manually extract them from the AppImage and add them as sources for the package, until someone comes with a clever idea some day.

Thanks for your help, I consider this resolved for now.
