### ISSUE TITLE
Building fails with nodejs 10

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy-labs/cozy-desktop#1054]
It stops at:
```
error /build/cozy-desktop/src/cozy-desktop-3.6.0/node_modules/elm-format: Command failed.
Exit signal: SIGABRT
Command: binwrap-install
Arguments: 
Directory: /build/cozy-desktop/src/cozy-desktop-3.6.0/node_modules/elm-format
Output:
node[1422]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [node]
 2: 0x56314d93b9db [node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [node]
 5: 0x56314db50ba7 [node]
 6: 0x56314db5133c [node]
 7: 0x22782838427d
```

I suppose this is an issue with elm-format, not cozy-desktop itself?

**Comment by sebn** [comment]
Yes, possibly a node 10 specific issue... (I didn't have the time to test it yet)

**Comment by ArchangeGabriel** [comment]
(Still happening with nodejs 10.1 for information)

**Comment by sebn** [comment]
Sorry for the late answer!

We'll definitely make sure it works on Node 10 at some point, but right now we only use and target Node 8 because this is what is embedded in the electron version we're using. The embedded node version is actually older than the current LTS, must be something like node 8.2.x. We aren't using electron 2.0 yet (which embeds node 8.9, still older than current LTS).

We used to build on multiple node versions, but it was really slowing down the development workflow and CI builds, so we decided to focus on the needed runtime.

If that makes sense, do you mind if I close the issue?

**Comment by ArchangeGabriel** [comment]
I understand this is not your priority, so I will build using the carbon LTS, but that means people might not be able to install cozy-desktop using the package on ArchLinux since the LTS will conflicts with packages requiring a newer version (like kresus on my case).

Anyway, since the application is barely usable right now, I would indeed prefer that you focus on development for the time being. ;)
